# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f39c90188dc33257e325dd0beecdf3993b620d9593241248ec26adeb08a89117df94a28363e93ef4c96933bb1657f971bc9b1cf84fc4d417296924b5e982ccb

test:
  secret_key_base: 6b0c1e3fb87ca70b11ba4f09a3a2a04adb5374b920763de4482e9d460ac0c6764230a4d39f325558929d977a5787d3864f52f7edd9bcf4b532ac8d9d462005e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
